version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    ignore:
      - dependency-name: "substrate-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "fork-tree"
      - dependency-name: "remote-externalities"
      - dependency-name: "pallet-*"
      - dependency-name: "beefy-*"
      - dependency-name: "try-runtime-*"
    schedule:
      interval: "daily"