[package]
name = "bsc-adapter"
version = "0.1.0"
edition = "2018"

[dependencies]
ws = { version = "0.9.1", optional = true, features = ["ssl"] }
ethabi = "14.1.0"
web3 = "0.16.0"
ethers-core = "0.2.2"
ethers-contract = "0.2.2"
tokio = { version = "1.0", optional = true, features = ["full"] }
async-trait = "0.1.50"
hex-literal = "0.3.3"
substrate-api-client = { git = "https://github.com/scs/substrate-api-client.git", rev = "672a5d4ed9f076525235fef6b5af288f666df803" }
runtime = {git = "https://github.com/RealisNetwork/Realis.Network.git", rev = "757d331d7af58bd5275ea71ccf13cf0c3f4f5d57", package = "node-runtime", default-features = false}

logger = { version = "0.1.0", path = "../logger" }

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-runtime"
default-features=false

[features]
default = ["std"]
std = [
    "ws",
    "tokio",
    "runtime/std"
]

# need to add this for the app_crypto macro
full_crypto = []