[package]
name = "bsc-adapter"
version = "0.1.0"
edition = "2018"

[dependencies]
ethabi = "14.1.0"
web3 = "0.16.0"
tokio = { version = "1.0" }
async-trait = "0.1.50"
logger = { version = "0.1.0", path = "../logger" }

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-runtime"