[package]
name = "realis-adapter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
runtime = { git = "https://github.com/RealisNetwork/Realis.Network.git", branch = "main", package = "node-runtime" }
substrate-api-client = { git = "https://github.com/scs/substrate-api-client.git", rev = "672a5d4ed9f076525235fef6b5af288f666df803" }
bsc-sender = { path = "../bsc-sender" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "master", package = "sp-core" }
system = { git = "https://github.com/paritytech/substrate.git", branch = "master", package = "frame-system" }
codec = { package = "parity-scale-codec", features = ["derive"], version = "2.0.0", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "runtime/std",
]
