[package]
name = "bsc-sender"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
log = "0.4"
realis-adapter = { version = "0.1.0", path = "../realis-adapter" }
runtime = { git = "https://github.com/RealisNetwork/Realis.Network.git", rev = "2e70b4b64fca49c6544173c05186c27c665a9103", package = "node-runtime" }
secp256k1 = { version = "0.20", features = ["recovery"] }
web3 = "0.16.0"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-core"
default-features = false
features = ["full_crypto"]

[features]
default = ["std"]
std = [
    "runtime/std"
]
