[package]
name = "bsc-sender"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
web3 = "0.16.0"
secp256k1 = { version = "0.20", features = ["recovery"], optional = true }
sp-core = { git = "https://github.com/paritytech/substrate.git", package = "sp-core", default-features = false }
runtime = { git = "https://github.com/RealisNetwork/Realis.Network.git", rev = "757d331d7af58bd5275ea71ccf13cf0c3f4f5d57", package = "node-runtime", default-features = false }
realis-adapter = { version = "0.1.0", path = "../realis-adapter" }
logger = { path = "../logger" }

[features]
default = ["std"]
std = [
    "secp256k1",
    "runtime/std"
]