[package]
name = "bsc-sender"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3"}
tokio = { version = "1.0", optional = true, features = ["full"] }
hex-literal = "0.3"
secp256k1 = { version = "0.20", features = ["recovery"], optional = true }

[features]
default = ["std"]
std = [
    "tokio",
    "secp256k1"
]