[package]
name = "bsc-sender"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = { version = "0.7", optional = true }
ws = { version = "0.9.1", optional = true, features = ["ssl"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
log = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
thiserror = { version = "1.0", optional =true }
primitive-types = { version = "0.6.1", optional = true, features = ["codec"] }
substrate-api-client = { git = "https://github.com/scs/substrate-api-client.git" }
web3 = "0.16.0"
binance = "0.16.2"
tokio = { version = "1.0", optional = true, features = ["full"] }
tokio-stream = { version = "0.1", optional = true }
tokio-util = { version = "0.6", optional = true, features = ["compat", "io"] }
hex-literal = "0.3"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-core"
default-features = false
features = ["full_crypto"]

[dependencies.codec]
package = "parity-scale-codec"
features = ["derive"]
version = "2.0.0"
default-features = false

[dev-dependencies]
hex-literal = "0.3"

[features]
default = ["std"]
std = [
    "codec/std",
    "serde/std",
    "serde_json",
    "env_logger",
    "log",
    "ws",
    "hex/std",
    "primitive-types",
    "thiserror",
    "tokio"
]

# need to add this for the app_crypto macro
full_crypto = []