[package]
name = "bridge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bsc-adapter = { version = "0.1.0", path = "../bsc-adapter" }
bsc-sender = { version = "0.1.0", path = "../bsc-sender" }
realis-adapter = { version = "0.1.0", path = "../realis-adapter" }
realis-sender = { version = "0.1.0", path = "../realis-sender" }
chrono = "0.4"
slog = { version = "2.7", features = ["release_max_level_trace", "max_level_trace"] }
slog-async = "2.5"
slog-envlogger = "2.2"
slog-json = "2.3"
slog-scope = "4.3"
slog-stdlog = "4.0"
tokio = { version = "1.0", optional = true, features = ["full"] }
futures = "0.3.16"

[features]
default = ["std"]
std = [
    "tokio"
]
