[package]
name = "bridge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realis-adapter = {version = "0.1.0", path = "../realis-adapter"}
bsc-sender = {version = "0.1.0", path = "../bsc-sender"}

tokio = { version = "1.0", optional = true, features = ["full"] }

[features]
default = ["std"]
std = [
    "tokio"
]