[package]
name = "bridge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Custom dependencies
realis-listener = { path = "../realis-listener" }
bsc-adapter = { path = "../bsc-adapter" }
primitives = { path = "../primitives" }
db = { path = "../db" }
#
rust-lib = { git = "https://github.com/RealisNetwork/rust-lib.git" }
tokio = { version = "1", features = ["full"] }
env_logger = "0.9.0"
futures = "0.3.16"
log = "0.4"
