[package]
name = "realis-sender"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
ws = { version = "0.9.1", optional = true, features = ["ssl"] }
web3 = "0.16.0"
sp-keyring = { git = "https://github.com/paritytech/substrate.git" }

substrate-api-client = { git = "https://github.com/scs/substrate-api-client.git", rev = "672a5d4ed9f076525235fef6b5af288f666df803" }
bsc-adapter = { version = "0.1.0", path = "../bsc-adapter" }
logger = { version = "0.1.0", path = "../logger" }


[dependencies.sp-core]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-core"
default-features = false
features = ["full_crypto"]

[features]
default = ["std"]
std = [
    "ws",
]
# need to add this for the app_crypto macro
full_crypto = []
