name: Check Set-Up & Build

on: push

env:
  RUST_BACKTRACE: 1

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-05-11
          target: wasm32-unknown-unknown
          components: rustfmt
      - run: make fmt check=yes

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-05-11
          target: wasm32-unknown-unknown
          components: clippy
      - run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-05-11 # Pinned because of compilation error on later version, should unpin later.
          target: wasm32-unknown-unknown
      - run: make build

# TODO: Run tests.